import json
import unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def read_text(path): return (ROOT / path).read_text(encoding="utf-8")
class ProjectContractTests(unittest.TestCase):
    def test_identity_and_minimal_permissions(self):
        manifest = json.loads(read_text("manifest.json.in"))
        cmake = read_text("CMakeLists.txt")
        self.assertEqual(manifest["name"], "nextdeck.cloudsite")
        self.assertEqual(manifest["title"], "NextDeck")
        self.assertIn('set(NEXTDECK_VERSION "0.1.0")', cmake)
        self.assertEqual(manifest["version"], "@NEXTDECK_VERSION@")
        self.assertEqual(manifest["architecture"], "$ENV{ARCH}")
        self.assertEqual(manifest["framework"], "$ENV{CLICK_FRAMEWORK}")
        self.assertIn("nextdeck", manifest["hooks"])
        self.assertEqual(manifest["hooks"]["nextdeck"]["content-hub"], "nextdeck-contenthub.json")
        apparmor = read_text("nextdeck.apparmor")
        self.assertIn('"accounts"', apparmor)
        self.assertIn('"content_exchange"', apparmor)
        self.assertIn('"content_exchange_source"', apparmor)
        self.assertIn('"networking"', apparmor)
        self.assertNotIn("unconfined", apparmor)
        self.assertNotIn("template", apparmor)
    def test_online_accounts_providers_are_declared(self):
        accounts = read_text("nextdeck.accounts")
        self.assertIn('"provider": "nextcloud"', accounts)
        self.assertIn('"provider": "owncloud"', accounts)
        self.assertIn("Use this Nextcloud account for NextDeck.", accounts)
    def test_runtime_files_and_docs_exist(self):
        for path in ["qml/Main.qml", "qml/pages/HomePage.qml", "qml/pages/CardDetailPage.qml", "qml/pages/AccountSelectionPage.qml", "qml/pages/SettingsPage.qml", "qml/pages/LanguageSelectionPage.qml", "qml/pages/AboutPage.qml", "qml/backend/AuthCore.js", "qml/backend/DeckApiClient.qml", "qml/backend/DeckCache.qml", "qml/backend/DeckController.qml", "qml/backend/DeckShareExportPage.qml", "qml/backend/DeckShareExportPageUbuntu.qml", "qml/backend/DeckAttachmentImportPage.qml", "qml/backend/DeckAttachmentImportPageUbuntu.qml", "qml/backend/DeckAttachmentOpenPage.qml", "qml/backend/DeckAttachmentOpenPageUbuntu.qml", "DeckNetwork.cpp", "DeckNetwork.h", "ContentHubBridge.cpp", "ContentHubBridge.h", "nextdeck-contenthub.json", "scripts/desktop-test.sh", "assets/logo.svg", "assets/openstore-banner.svg", "README.md", "CHANGELOG.md", "LICENSE"]:
            self.assertTrue((ROOT / path).exists(), path)
        gitmodules = read_text(".gitmodules")
        self.assertIn('[submodule "vendor/NextCommon"]', gitmodules)
        self.assertIn("path = vendor/NextCommon", gitmodules)
        self.assertIn("url = https://github.com/EtherGhost/NextCommon.git", gitmodules)
        for path in ["vendor/NextCommon/README.md", "vendor/NextCommon/qml/NextCommon/AboutPage.qml", "vendor/NextCommon/qml/NextCommon/LanguagePage.qml", "vendor/NextCommon/qml/NextCommon/AccountPage.qml", "vendor/NextCommon/qml/NextCommon/AccountSessionAdapter.qml", "vendor/NextCommon/qml/NextCommon/MainTopBar.qml", "vendor/NextCommon/qml/NextCommon/DrawerShell.qml", "vendor/NextCommon/qml/NextCommon/DrawerNavItem.qml", "vendor/NextCommon/qml/NextCommon/AvatarButton.qml", "vendor/NextCommon/qml/NextCommon/EmptyState.qml", "vendor/NextCommon/qml/NextCommon/ReorderableListView.qml", "vendor/NextCommon/docs/integration-guide.md"]:
            self.assertTrue((ROOT / path).exists(), path)
        self.assertNotIn("AndroidNextcloudDeckReference", read_text("README.md"))
        self.assertIn("nextdeckAppVersion", read_text("qml/pages/AboutPage.qml"))
        self.assertIn("NextCommon.AboutPage", read_text("qml/pages/AboutPage.qml"))
        self.assertIn("NextCommon.LanguagePage", read_text("qml/pages/LanguageSelectionPage.qml"))
        self.assertIn('Version %1', read_text("vendor/NextCommon/qml/NextCommon/AboutPage.qml"))

    def test_release_qml_has_no_runtime_console_logging(self):
        qml_paths = list((ROOT / "qml").rglob("*.qml")) + list((ROOT / "vendor/NextCommon/qml").rglob("*.qml"))
        combined = "\n".join(path.read_text(encoding="utf-8") for path in qml_paths)
        self.assertNotIn("console.log", combined)
    def test_online_accounts_flow_contract(self):
        account_page = read_text("qml/pages/AccountSelectionPage.qml")
        common_account = read_text("vendor/NextCommon/qml/NextCommon/AccountPage.qml")
        common_session = read_text("vendor/NextCommon/qml/NextCommon/AccountSessionAdapter.qml")
        account_combined = account_page + "\n" + common_account
        qrc = read_text("qml/qml.qrc")
        self.assertIn("NextCommon.AccountPage", account_page)
        self.assertIn('appApplicationId: "nextdeck.cloudsite_nextdeck"', account_page)
        self.assertIn('nextcloudServiceId: "nextdeck.cloudsite_nextdeck_nextcloud"', account_page)
        self.assertIn('owncloudServiceId: "nextdeck.cloudsite_nextdeck_owncloud"', account_page)
        self.assertIn("onAccountAuthorized", account_page)
        self.assertNotIn("service-not-enabled", account_combined)
        self.assertIn("System Settings > Accounts", account_combined)
        self.assertIn("openSystemAccountsDialog", account_combined)
        self.assertIn("function systemAccountsDialogText()", account_combined)
        self.assertIn("function retryAfterSystemApproval()", account_combined)
        self.assertIn("waitingForSystemApproval", account_combined)
        self.assertIn("selectedHasServiceHandle", account_combined)
        self.assertIn("serviceResolutionRetryCount", account_combined)
        self.assertIn("maxServiceResolutionRetries", account_combined)
        self.assertIn("serviceResolutionRetryTimer", account_combined)
        self.assertIn("function retryServiceResolutionBeforePrompt()", account_combined)
        self.assertIn("function expectedServiceIdForProvider(providerId)", account_combined)
        self.assertIn("function isExpectedAppService(serviceId, providerId)", account_combined)
        self.assertNotIn('OnlineAccountsAuthorization waiting-for-service', account_combined)
        self.assertNotIn('OnlineAccountsAuthorization retry-after-auth-error', account_combined)
        self.assertNotIn('OnlineAccountsAuthorization repair-signon-access', account_combined)
        self.assertNotIn("Lomiri.OnlineAccounts.Client", account_combined)
        self.assertNotIn("\n    Setup {", account_combined)
        self.assertNotIn("accountSetup.exec()", account_combined)
        self.assertIn("function openSystemAccountsSettings()", account_combined)
        self.assertIn('Qt.openUrlExternally("settings:///system/online-accounts")', account_combined)
        self.assertNotIn("function openSystemAccounts()", account_combined)
        self.assertNotIn("repairSignOnAccessBeforePrompt", account_combined)
        self.assertNotIn("signOnRepairAttemptCount", account_combined)
        self.assertIn("selectedEnabled || selectedHasServiceHandle", account_combined)
        self.assertIn("if (!selectedEnabled && !selectedHasServiceHandle)", account_combined)
        self.assertNotIn('var enabled = accountServices.get(i, "enabled")', common_session)
        self.assertNotIn("serviceId === serviceIdSetting && enabled", common_session)
        self.assertIn("verify it automatically", account_combined)
        self.assertIn('i18n.tr("Allow account access")', account_combined)
        self.assertIn("Open Ubuntu Touch System Settings manually", account_combined)
        self.assertIn("function clearSelectedAccount()", account_combined)
        self.assertNotIn("select it again", account_combined)
        self.assertIn("function restoreSelectedAccountFromSettings()", account_combined)
        self.assertIn("accountSettings.accountId === row.role(\"accountId\")", account_combined)
        self.assertIn("accountSettings.serviceId === rowServiceId", account_combined)
        self.assertIn("authorizationRunning", account_combined)
        self.assertIn("if (page.authorizationRunning)", account_combined)
        self.assertIn("page.selectAccount(", account_combined)
        self.assertNotIn("Discovered services:", account_combined)
        self.assertNotIn("Diagnostics", account_combined)
        self.assertNotIn('text: row.isSelected ? i18n.tr("Selected") : i18n.tr("Use")', account_combined)
        self.assertNotIn('selectedService.updateServiceEnabled(true)', account_combined)
        self.assertIn('page.commitServerUrlInput("authenticate")', account_combined)
        self.assertIn("<file>backend/AuthCore.js</file>", qrc)
        self.assertNotIn("<file>backend/AccountSessionAdapter.qml</file>", qrc)
        self.assertIn('<file alias="NextCommon/AccountSessionAdapter.qml">../vendor/NextCommon/qml/NextCommon/AccountSessionAdapter.qml</file>', qrc)
    def test_desktop_test_and_api_contract(self):
        main = read_text("main.cpp")
        cmake = read_text("CMakeLists.txt")
        script = read_text("scripts/desktop-test.sh")
        api = read_text("qml/backend/DeckApiClient.qml")
        deck_network = read_text("DeckNetwork.cpp")
        qrc = read_text("qml/qml.qrc")
        self.assertIn("NEXTDECK_DESKTOP_TEST_AUTH", main)
        self.assertIn("configBool(desktopEnv, \"NEXTDECK_DESKTOP_DARK_MODE\", true)", main)
        self.assertIn("NEXTDECK_DESKTOP_DARK_MODE", script)
        self.assertIn("os.environ.get(\"NEXTDECK_DESKTOP_DARK_MODE\", \"1\")", script)
        self.assertIn("#include \"DeckNetwork.h\"", main)
        self.assertIn("DeckNetwork deckNetwork", main)
        self.assertIn("deckNetwork", main)
        self.assertIn("find_package(Qt5Network REQUIRED)", cmake)
        self.assertIn("DeckNetwork.cpp DeckNetwork.h", cmake)
        self.assertIn("Qt5::Network", cmake)
        self.assertIn("NEXTCLOUD_TEST_SERVER", main)
        self.assertIn("NEXTNEWS_TEST_SERVER", script)
        self.assertIn("QNetworkAccessManager *DeckNetwork::isolatedManager()", deck_network)
        self.assertIn("return new QNetworkAccessManager(this)", deck_network)
        self.assertIn('request.setRawHeader("Authorization"', deck_network)
        self.assertIn('request.setRawHeader("OCS-APIRequest", "true")', deck_network)
        self.assertIn('request.setRawHeader("Accept", "application/json")', deck_network)
        self.assertIn('request.setRawHeader("Connection", "close")', deck_network)
        self.assertIn("/index.php/apps/deck/api/v1.0/boards", api)
        self.assertIn("/stacks", api)
        self.assertIn("/cards/", api)
        self.assertIn("GET", api)
        self.assertIn("POST", api)
        self.assertIn("PUT", api)
        self.assertIn("DELETE", api)
        self.assertIn("function loadBoard(", api)
        self.assertNotIn("function boardSummary(", api)
        self.assertIn("function authenticatedUrl(", api)
        self.assertIn("typeof deckNetwork", api)
        self.assertIn("deckNetwork.sendRequest", api)
        self.assertIn("deckNetwork.fetchDataUrl", api)
        self.assertIn("deckNetwork.uploadFileMultipart", api)
        self.assertIn("deckNetwork.downloadFileToCache", api)
        self.assertIn("signal avatarLoaded(string userId, string dataUrl, int generation)", api)
        self.assertIn("signal attachmentUploaded(var card, var attachment, int generation)", api)
        self.assertIn("signal attachmentDownloaded(var card, var attachment, string fileUrl, string fileName, string mimeType, int generation)", api)
        self.assertIn("function loadAvatar(", api)
        self.assertIn("function handleNativeDataUrlFinished(", api)
        self.assertIn("function handleNativeFileDownloaded(", api)
        self.assertIn("void DeckNetwork::fetchDataUrl", deck_network)
        self.assertIn("void DeckNetwork::uploadFileMultipart", deck_network)
        self.assertIn("void DeckNetwork::downloadFileToCache", deck_network)
        self.assertIn("AttachmentDownloads", deck_network)
        self.assertIn("QHttpMultiPart::FormDataType", deck_network)
        self.assertIn('form-data; name=\\"type\\"', deck_network)
        self.assertIn('form-data; name=\\"file\\"; filename=', deck_network)
        self.assertIn('form-data; name=\\"data\\"', deck_network)
        self.assertIn("safeMultipartFileName(fileName.trimmed().isEmpty()", deck_network)
        self.assertIn("dataUrlFinished(requestId, dataUrl, generation)", deck_network)
        self.assertIn("function nativeRequest(", api)
        self.assertIn("function handleNativeRequestFinished(", api)
        self.assertNotIn("function handleIdentityResponse(", api)
        self.assertIn("authenticatedUrl(url, userName)", api)
        self.assertIn("function createCard(", api)
        self.assertIn("function updateCard(", api)
        self.assertIn("function reorderCard(", api)
        self.assertIn("function ownerUid(", api)
        self.assertIn("payload.owner = ownerValue", api)
        self.assertIn("function isDeletedEntity(", api)
        self.assertIn("isDeletedEntity(boards[i])", api)
        self.assertIn("isDeletedEntity(stack)", api)
        self.assertIn("function stackEntriesFromResponse(", api)
        self.assertIn("cardArchived(var card, bool archived, int generation)", api)
        self.assertIn("card.archived && includeArchivedCards !== true", api)
        self.assertIn("entry.archived = card.archived === true || includeArchivedCards === true", api)
        self.assertIn('"/stacks/archived"', api)
        self.assertIn("function archiveCard(", api)
        self.assertIn('"/reorder"', api)
        self.assertIn("function deleteCard(", api)
        self.assertIn("function createBoard(", api)
        self.assertIn("function updateBoard(", api)
        self.assertIn("function deleteBoard(", api)
        self.assertIn("function searchSharees(", api)
        self.assertIn("/ocs/v2.php/core/autocomplete/get", api)
        self.assertIn("function createAccessControl(", api)
        self.assertIn("function updateAccessControl(", api)
        self.assertIn("function deleteAccessControl(", api)
        self.assertIn('"/index.php/apps/deck/api/v1.0/boards/" + encodeURIComponent(boardId) + "/acl"', api)
        self.assertNotIn('"/ocs/v2.php/apps/deck/api/v1.0/boards/" + encodeURIComponent(boardId) + "/acl?format=json"', api)
        self.assertIn('"/acl/"', api)
        self.assertIn("signal boardAccessUpdated(var board, string message, int generation)", api)
        self.assertIn("signal shareesLoaded(var sharees, int generation)", api)
        self.assertIn("function createStack(", api)
        self.assertIn("function updateStack(", api)
        self.assertIn("function deleteStack(", api)
        self.assertIn("function loadCardDetails(", api)
        self.assertIn("/index.php/apps/deck/api/v1.1/boards/", api)
        self.assertIn("function assignLabel(", api)
        self.assertIn("function assignUser(", api)
        self.assertIn('requestForm(url, userName, secret, "PUT", {"type": 0, "userId": userId || ""}, i18n.tr("user assignment")', api)
        self.assertIn('"_labelsAuthoritative": backup._labelsAuthoritative === true', api)
        self.assertIn('"_assignedUsersAuthoritative": backup._assignedUsersAuthoritative === true', api)
        self.assertIn('"kind": kind || "json"', api)
        self.assertIn('if (pending.kind === "form")', api)
        self.assertIn("function loadComments(", api)
        self.assertIn("function deleteComment(", api)
        self.assertIn("/ocs/v2.php/apps/deck/api/v1.0/cards/", api)
        self.assertIn("/comments?format=json", api)
        self.assertIn("function loadActivities(", api)
        self.assertIn("/ocs/v2.php/apps/activity/api/v2/activity/filter", api)
        self.assertIn("object_type=deck_card", api)
        self.assertIn("sort=asc", api)
        self.assertIn("function normalizeActivity(activity)", api)
        self.assertIn("function loadAttachments(", api)
        self.assertIn("function uploadAttachment(", api)
        self.assertIn("function deleteAttachment(", api)
        self.assertIn("/attachments", api)
        self.assertIn('"?type=" + encodeURIComponent(type)', api)
        self.assertIn('i18n.tr("attachment delete")', api)
        self.assertIn('contentHubBridge.isReadableLocalFile(fileUrl)', api)
        self.assertIn('contentHubBridge.fileSize(fileUrl)', api)
        self.assertIn('i18n.tr("The selected file is empty.")', api)
        self.assertNotIn("GET attachments count=", api)
        self.assertIn("function mergeAttachments(existing, incoming)", api)
        self.assertIn("function normalizeAttachment(attachment)", api)
        self.assertIn("extended.info", api)
        self.assertIn("normalized.basename", api)
        self.assertIn("updated.attachments = mergeAttachments(card.attachments || [], normalizeAttachments(responseArray(data, \"attachments\")))", api)
        self.assertIn('"attachment upload"', api)
        controller = read_text("qml/backend/DeckController.qml")
        bridge_header = read_text("ContentHubBridge.h")
        bridge_cpp = read_text("ContentHubBridge.cpp")
        adapter = read_text("vendor/NextCommon/qml/NextCommon/AccountSessionAdapter.qml")
        home = read_text("qml/pages/HomePage.qml")
        account_page = read_text("qml/pages/AccountSelectionPage.qml")
        app_controller = read_text("qml/backend/AppController.qml")
        self.assertIn("signal accountChanged", app_controller)
        self.assertIn("page.appController.accountChanged(", account_page)
        self.assertIn("onAccountChanged: function(accountId, displayName, providerId, serviceId, serverUrl, avatarUrl)", home)
        self.assertIn("dataController.applyAccountSelection(accountId, displayName, providerId, serviceId, serverUrl, avatarUrl)", home)
        self.assertIn("function applyAccountSelection(", controller)
        self.assertIn("NextCommon.AccountSessionAdapter", controller)
        self.assertIn('logPrefix: "NextDeck"', controller)
        self.assertIn("session.setAccount(", controller)
        self.assertIn("function setAccount(", adapter)
        self.assertIn("var accountChanged = currentAccountId !== accountId", adapter)
        self.assertIn("cachedSecret = \"\"", adapter)
        self.assertIn("pendingCallback = null", adapter)
        self.assertIn("authenticateAfterHandleTimer.restart()", adapter)
        self.assertIn("onTriggered: accountService.authenticate({})", adapter)
        self.assertIn("signal authenticated(string userName, string secret, string serverUrl, int accountId, string serviceId)", adapter)
        self.assertIn("function pendingAuthMatchesCurrent()", adapter)
        self.assertIn("property string logPrefix", adapter)
        self.assertIn("function handleAccountChanged()", controller)
        self.assertIn("property bool applyingAccountSelection: false", controller)
        self.assertIn("property int accountRequestGeneration: 0", controller)
        self.assertIn("function stopAccountActivity()", controller)
        self.assertIn("function isCurrentApiGeneration(generation)", controller)
        self.assertIn("if (!controller.isCurrentApiGeneration(generation))", controller)
        self.assertIn("property bool settingsReady", controller)
        self.assertIn("if (controller.settingsReady && !controller.applyingAccountSelection) controller.handleAccountChanged()", controller)
        self.assertIn("var newKey = accountKeyFor(accountId, providerId, serviceId, serverUrl)", controller)
        self.assertIn("activeAccountKey = newKey", controller)
        self.assertIn("skipNextCachedLoad = true", controller)
        self.assertIn("cache.clearCleanServerDataForCurrentScope()", controller)
        self.assertIn("function hasCompleteAccountSettings()", controller)
        self.assertIn("function desktopTestAuthActive()", controller)
        self.assertIn("desktopTestAuthActive() ? -1 : accountSettings.accountId", controller)
        self.assertIn('desktopTestAuthActive() ? "desktop-test-env" : accountSettings.serviceId', controller)
        self.assertIn("Qt.callLater(controller.refresh)", controller)
        self.assertIn("if (!hasCompleteAccountSettings())", controller)
        self.assertIn("function accountKeyFor(", controller)
        self.assertIn("function clearAccountData()", controller)
        self.assertIn("property var avatarDataUrls", controller)
        self.assertIn("function avatarDataUrl(userId)", controller)
        self.assertIn("function requestAvatar(userId)", controller)
        self.assertIn("function refreshAll()", controller)
        self.assertIn("property bool refreshBoardsFirst: false", controller)
        self.assertIn("if (controller.refreshBoardsFirst)", controller)
        self.assertIn("function openBoard(", controller)
        self.assertIn("function openPreferredBoard(", controller)
        self.assertIn("function removeBoardEntry(boardId)", controller)
        self.assertIn("property int lastBoardId", controller)
        self.assertIn("property string lastBoardByAccountJson", controller)
        self.assertIn("function saveLastBoardForCurrentAccount(", controller)
        self.assertIn("function lastBoardForCurrentAccount()", controller)
        self.assertIn("saveLastBoardForCurrentAccount(selectedBoardId, selectedBoardTitle)", controller)
        self.assertIn("function goBackToBoards()", controller)
        self.assertIn("function saveCard(", controller)
        self.assertIn("function resolveConflictUseServer(", controller)
        self.assertIn("function resolveConflictKeepLocal(", controller)
        self.assertIn("function createCard(", controller)
        self.assertIn("function deleteCard(", controller)
        self.assertIn("function uploadAttachment(", controller)
        self.assertIn("function deleteAttachments(", controller)
        self.assertIn("function openAttachment(", controller)
        self.assertIn("signal attachmentReadyToOpen", controller)
        self.assertIn("function deleteNextAttachmentIfNeeded(card)", controller)
        self.assertIn("function attachmentKey(attachment)", controller)
        self.assertIn('"fileName": fileName || ""', controller)
        self.assertIn('pendingOperation === "uploadAttachment"', controller)
        self.assertIn('pendingOperation === "deleteAttachment"', controller)
        self.assertIn('pendingOperation === "downloadAttachment"', controller)
        self.assertIn("onAttachmentUploaded", controller)
        self.assertIn("onAttachmentDeleted", controller)
        self.assertIn("onAttachmentDownloaded", controller)
        self.assertNotIn("controller.loadAttachments(updated)", controller)
        self.assertIn("function moveCardToStack(", controller)
        self.assertIn("function applyCardOrder(", controller)
        self.assertIn("function saveCardOrder(", controller)
        self.assertIn("entries = updatedEntries", controller)
        self.assertIn("cache.saveBoardEntries(selectedBoardId, entries)", controller)
        self.assertIn('pendingOperation === "reorderCard"', controller)
        self.assertIn('statusText = i18n.tr("Card order saved.")', controller)
        save_order_body = controller.split("function saveCardOrder(", 1)[1].split("function syncDirtySoon(", 1)[0]
        self.assertNotIn("loading = true", save_order_body)
        self.assertNotIn('controller.refresh()\\n        }\\n        onCardDeleted', controller)
        self.assertIn("property string currentUserName", controller)
        self.assertIn("function insertCardEntry(", controller)
        self.assertIn("function replaceCardEntry(", controller)
        self.assertIn("function removeCardEntry(", controller)
        self.assertIn('property string viewMode: "boards"', controller)
        self.assertIn("function accountKey()", controller)
        self.assertIn("onAccountIdChanged: if (controller.settingsReady && !controller.applyingAccountSelection) controller.handleAccountChanged()", controller)
        self.assertIn("property string syncStateText", controller)
        self.assertIn("property string syncStateColor", controller)
        self.assertIn("<file>backend/DeckApiClient.qml</file>", qrc)
        self.assertIn("<file>backend/DeckCache.qml</file>", qrc)
        self.assertIn("<file>backend/DeckController.qml</file>", qrc)
        self.assertIn("<file>backend/DeckShareExportPage.qml</file>", qrc)
        self.assertIn("<file>backend/DeckShareExportPageUbuntu.qml</file>", qrc)
        self.assertIn("<file>backend/DeckAttachmentImportPage.qml</file>", qrc)
        self.assertIn("<file>backend/DeckAttachmentImportPageUbuntu.qml</file>", qrc)
        self.assertIn("<file>backend/DeckAttachmentOpenPage.qml</file>", qrc)
        self.assertIn("<file>backend/DeckAttachmentOpenPageUbuntu.qml</file>", qrc)
        self.assertIn("Q_INVOKABLE bool isReadableLocalFile", bridge_header)
        self.assertIn("Q_INVOKABLE QString fileName", bridge_header)
        self.assertIn("Q_INVOKABLE qint64 fileSize", bridge_header)
        self.assertIn("Q_INVOKABLE QString mimeType", bridge_header)
        self.assertIn("Q_INVOKABLE QUrl copyImportedFileToCache", bridge_header)
        self.assertIn("QMimeDatabase", bridge_cpp)
        self.assertIn("ContentHubIncoming", bridge_cpp)
        self.assertIn('alias="NextCommon/AvatarButton.qml"', qrc)
        self.assertIn('alias="NextCommon/EmptyState.qml"', qrc)
        self.assertIn('alias="NextCommon/AboutPage.qml"', qrc)
        self.assertIn('alias="NextCommon/LanguagePage.qml"', qrc)
        self.assertIn('alias="NextCommon/AccountPage.qml"', qrc)
        self.assertIn('alias="NextCommon/MainTopBar.qml"', qrc)
        self.assertIn('alias="NextCommon/DrawerShell.qml"', qrc)
        self.assertIn('alias="NextCommon/DrawerNavItem.qml"', qrc)
        self.assertIn('alias="NextCommon/SettingsShell.qml"', qrc)
        self.assertIn('alias="NextCommon/SettingsCard.qml"', qrc)
        self.assertIn('alias="NextCommon/StatusRow.qml"', qrc)
        self.assertIn('alias="NextCommon/ConfirmDialog.qml"', qrc)
        self.assertIn('alias="NextCommon/ReorderableListView.qml"', qrc)
        self.assertIn('alias="NextCommon/DateFormat.js"', qrc)
        self.assertIn("<file>pages/CardDetailPage.qml</file>", qrc)
        self.assertIn("property int requestGeneration: 0", api)
        self.assertIn("signal boardsLoaded(var entries, int generation)", api)
    def test_home_top_bar_contract(self):
        home = read_text("qml/pages/HomePage.qml")
        self.assertIn('import "qrc:/NextCommon" as NextCommon', home)
        self.assertIn("contents: NextCommon.MainTopBar", home)
        self.assertIn("NextCommon.DrawerShell", home)
        self.assertIn("appName: appController.appName", home)
        self.assertIn("onBottomItemClicked: page.openPage(pageUrl)", home)
        self.assertIn("onMenuClicked: page.drawerOpen = true", home)
        self.assertIn("onFilterClicked: page.beginFilterDraft()", home)
        self.assertIn("onStatusClicked: PopupUtils.open(statusDetailsDialog)", home)
        self.assertIn("NextCommon.EmptyState", home)
        self.assertIn('i18n.tr("Search in %1")', home)
        self.assertNotIn('iconName: "reload"', home)
        self.assertIn("statusDetailsDialog", home)
        self.assertIn("filterDialog", home)
        self.assertIn('property string filterTab: "tags"', home)
        self.assertIn("property string draftFilterDueMode", home)
        self.assertIn("function beginFilterDraft()", home)
        self.assertIn("function resetFilterDraft()", home)
        self.assertIn("function applyFilterDraft()", home)
        self.assertIn("function filterActive()", home)
        self.assertIn("function resetFilters()", home)
        self.assertIn("function stackEntries()", home)
        self.assertIn("function activeStackEntry()", home)
        self.assertIn("function selectStack(", home)
        self.assertIn("function moveActiveStackRight()", home)
        self.assertIn("function canMoveActiveStackRight()", home)
        self.assertIn("function showCardOptions(", home)
        self.assertIn("function cardShareLink(", home)
        self.assertIn("function shareSelectedCardLink()", home)
        self.assertIn("function shareSelectedCardContent()", home)
        self.assertIn("function archiveSelectedCard()", home)
        self.assertIn("function showBoardOptionsDialog(board)", home)
        self.assertIn("function archiveSelectedBoard(archived)", home)
        self.assertIn("deleteBoardConfirmDialog", home)
        self.assertIn('i18n.tr("Archive board")', home)
        self.assertIn('i18n.tr("Restore board")', home)
        self.assertIn('i18n.tr("Delete board")', home)
        self.assertIn("property bool showArchivedBoardsMode", home)
        self.assertIn("property var visibleBoardEntries", home)
        self.assertIn("function updateVisibleBoardEntries()", home)
        self.assertIn("model: page.visibleBoardEntries", home)
        self.assertIn("(source[i].archived === true) === showArchivedBoardsMode", home)
        self.assertNotIn("function beginCardDrag(card, sceneY)", home)
        self.assertNotIn("function updateCardDrag(sceneY)", home)
        self.assertNotIn("function finishCardDrag()", home)
        self.assertNotIn("function cancelCardDrag()", home)
        self.assertNotIn("property bool cardDragActive", home)
        self.assertNotIn("property bool cardDragPointerCaptured", home)
        self.assertNotIn("cardDropBeforeKey", home)
        self.assertNotIn("cardDropAfterKey", home)
        self.assertNotIn("manualDragOffsetY", home)
        self.assertIn("NextCommon.ReorderableListView", home)
        self.assertIn("delegate: reorderCardDelegate", home)
        self.assertIn("property var visibleCardEntries", home)
        self.assertIn("function updateVisibleCardEntries()", home)
        self.assertIn("model: page.visibleCardEntries", home)
        self.assertNotIn("model: page.visibleCards()", home)
        self.assertIn("dragAreaRightMargin", home)
        self.assertIn('visible: dataController.viewMode === "cards"', home)
        self.assertIn("onMoveRequested: function(fromIndex, toIndex)", home)
        self.assertIn("function reorderVisibleCards(fromIndex, toIndex)", home)
        self.assertIn("var cards = visibleCards()", home)
        self.assertIn("visibleCardEntries = cards.slice(0)", home)
        self.assertNotIn("&& !dataController.loading\n                model: page.filteredEntries", home)
        self.assertIn('interactive: dataController.viewMode !== "cards"', home)
        self.assertIn('boundsBehavior: dataController.viewMode === "cards"', home)
        self.assertIn('if (dataController.viewMode !== "cards"\n                    && contentY < -page.pullRefreshThreshold', home)
        self.assertIn('opacity: dataController.viewMode !== "cards"', home)
        self.assertIn("dataController.saveCardOrder(moved, toIndex)", home)
        self.assertNotIn("filteredEntries = cards", home)
        self.assertIn("dataController.refreshAll()", home)
        self.assertIn("property bool cardPullToRefreshEnabled: true", home)
        self.assertNotIn("function resetCardsViewportSoon()", home)
        self.assertNotIn("resetCardsViewportTimer", home)
        self.assertNotIn("resetCardsViewportSettledTimer", home)
        self.assertNotIn("onLoadingChanged", home)
        self.assertNotIn("contentFlickable.contentY = 0", home)
        self.assertIn("Flickable.StopAtBounds", home)
        self.assertIn("Flickable.DragOverBounds", home)
        self.assertIn("pullToRefreshEnabled: page.cardPullToRefreshEnabled", home)
        self.assertIn("pullRefreshThreshold", home)
        self.assertIn("Pull to refresh", home)
        self.assertIn("Release to refresh", home)
        self.assertIn("Refreshing...", home)
        self.assertIn("cardOptionsDialog", home)
        self.assertIn("moveCardDialog", home)
        self.assertIn("wrapMode: Text.WordWrap", home)
        self.assertIn("maximumLineCount: 6", home)
        self.assertNotIn("[modelData.subtitle || \"\", modelData.detail || \"\"]", home)
        self.assertIn('if (dataController.viewMode === "boards")', home)
        self.assertIn('i18n.tr("Open the menu and choose a board.")', home)
        self.assertIn("function dueModeMatches(", home)
        self.assertIn("function doneModeMatches(", home)
        self.assertIn("function labelsMatch(", home)
        self.assertIn("function usersMatch(", home)
        topbar = read_text("vendor/NextCommon/qml/NextCommon/MainTopBar.qml")
        self.assertIn("filterCanvas", topbar)
        self.assertIn("statusCanvas", topbar)
        self.assertIn("signal menuClicked()", topbar)
        self.assertIn("signal searchChanged(string text)", topbar)
        self.assertIn("signal filterClicked()", topbar)
        self.assertIn("signal statusClicked()", topbar)
        self.assertIn("signal accountClicked()", topbar)
        self.assertIn("stackTabs", home)
        self.assertIn("page.activeStackEntry()", home)
        self.assertIn('category: "deck-ui"', home)
        self.assertIn("lastStackByBoardJson", home)
        self.assertIn("function saveLastStackForCurrentBoard(", home)
        self.assertIn("function lastStackForCurrentBoard()", home)
        self.assertIn("saveLastStackForCurrentBoard(activeStackId)", home)
        self.assertIn('i18n.tr("Create a card in %1.")', home)
        self.assertIn('i18n.tr("Search in %1")', home)
        self.assertIn('i18n.tr("Add card")', home)
        self.assertIn('i18n.tr("Add list")', home)
        self.assertIn('i18n.tr("Move list right")', home)
        self.assertIn('i18n.tr("Delete list")', home)
        self.assertIn('i18n.tr("Share link")', home)
        self.assertIn('i18n.tr("Share content")', home)
        self.assertIn('i18n.tr("Assign card to me")', home)
        self.assertIn('i18n.tr("Move card")', home)
        self.assertIn('i18n.tr("Archive card")', home)
        self.assertIn('i18n.tr("Delete card")', home)
        self.assertIn("page.stackOptions()", home)
        self.assertIn('i18n.tr("Filter")', home)
        self.assertIn('i18n.tr("Cancel")', home)
        self.assertIn('i18n.tr("Reset")', home)
        self.assertIn('i18n.tr("Tags")', home)
        self.assertIn('i18n.tr("Users")', home)
        self.assertIn('i18n.tr("Done")', home)
        self.assertIn('i18n.tr("Due date")', home)
        self.assertIn('i18n.tr("Overdue")', home)
        self.assertIn('i18n.tr("Tomorrow")', home)
        self.assertIn('i18n.tr("Next 7 days")', home)
        self.assertIn('i18n.tr("No due date")', home)
        self.assertIn("function statusIconKind()", home)
        self.assertIn("function statusAccentColor()", home)
        self.assertIn("function statusDetailsText()", home)
        self.assertIn('i18n.tr("Sync status")', home)
        avatar_button = read_text("vendor/NextCommon/qml/NextCommon/AvatarButton.qml")
        self.assertIn("OpacityMask", avatar_button)
        self.assertIn("avatarSource", avatar_button)
        self.assertIn("dataController.openBoard", home)
        self.assertNotIn("visible: false", home)
        self.assertIn("function openCard(", home)
        self.assertIn("function showCreateCardDialog(", home)
        self.assertIn("function showCreateBoardDialog(", home)
        self.assertIn("function showCreateListDialog(", home)
        self.assertIn("function showListOptions(", home)
        self.assertIn("createCardDialog", home)
        self.assertIn("createBoardDialog", home)
        self.assertIn("createListDialog", home)
        self.assertIn("listOptionsDialog", home)
        self.assertIn("dataController.createCard", home)
        self.assertIn("dataController.createBoard", home)
        self.assertIn("dataController.createStack", home)
        self.assertIn("dataController.updateStack", home)
        self.assertIn("dataController.deleteStack", home)
        self.assertIn("page.openCard(cardItem.cardData)", home)
        self.assertIn('i18n.tr("Language")', home)
        self.assertIn('i18n.tr("Account")', home)
        self.assertIn('i18n.tr("Settings")', home)
        self.assertIn('i18n.tr("About")', home)
        settings = read_text("qml/pages/SettingsPage.qml")
        self.assertIn("NextCommon.SettingsShell", settings)
        self.assertIn("NextCommon.SettingsCard", settings)
        self.assertIn('i18n.tr("Sync while app is active")', settings)
        self.assertIn('i18n.tr("Active sync interval")', settings)
        self.assertIn('i18n.tr("Cards")', settings)
        self.assertNotIn("These settings are placeholders", settings)
    def test_language_structure_matches_suite(self):
        language = read_text("qml/pages/LanguageSelectionPage.qml")
        for locale in ["", "en", "sv", "da", "de", "es", "fi", "fr", "it", "nb", "nl", "pl", "ru", "uk"]:
            self.assertIn('"code": "%s"' % locale, language)
        for po_file in ["da.po", "de.po", "es.po", "fi.po", "fr.po", "it.po", "nb.po", "nl.po", "pl.po", "ru.po", "uk.po"]:
            self.assertTrue((ROOT / "po" / po_file).exists(), po_file)
            self.assertIn("AI-assisted starter translation", read_text("po/" + po_file))
    def test_card_detail_contract(self):
        detail = read_text("qml/pages/CardDetailPage.qml")
        for snippet in [
            "property var deckController",
            'placeholderText: i18n.tr("Untitled card")',
            'i18n.tr("Description")',
            "id: autoSaveTimer",
            "function saveCard(manageFocus)",
            "id: conflictDialog",
            "function conflictPreviewText()",
            "function resolveSelectedConflictVersion()",
            "deckController.resolveConflictUseServer(page.card)",
            "deckController.resolveConflictKeepLocal(page.card)",
            "function deleteCard()",
            "function openAttachmentPicker()",
            "function openAttachment(attachment)",
            "function openDownloadedAttachment(fileUrl, fileName, mimeType)",
            "function deleteSelectedAttachments()",
            "deckController.saveCard(updated)",
            "deckController.deleteCard(page.card)",
            "deckController.uploadAttachment(page.card, uploadUrl, fileName)",
            "deckController.openAttachment(page.card, attachment)",
            "deckController.deleteAttachments(page.card, selected)",
            "deckController.loadComments(page.card)",
            "deckController.loadActivities(page.card)",
            "deckController.addComment(page.card",
            "deckController.deleteComments(page.card, selected)",
            "function commentRows()",
            "function sendComment()",
            "function sendCommittedComment()",
            "function toggleCommentSelection(comment)",
            "function deleteSelectedComments()",
            "function selectedCommentCount()",
            "id: commentCommitTimer",
            "id: commentComposer",
            "deleteCommentsDialog",
            "property bool commentSelectionMode",
            "property var selectedComments",
            "commentComposerHeight",
            'placeholderText: i18n.tr("Add comment")',
            "commentSectionTitle(comment)",
            "function activityRows()",
            "function activityText(activity)",
            "function activitySymbol(activity)",
            'text: i18n.tr("No activity yet.")',
            "deleteCardDialog",
            "deleteAttachmentsDialog",
            "Qt.inputMethod.commit()",
            "oskOverlap",
            "bottomMargin: page.oskOverlap",
            "contentColumn.childrenRect.height + units.gu(3) + page.oskOverlap",
            "bottomMargin: page.oskOverlap + page.commentComposerHeight",
            "datePickerDialog",
            "timePickerDialog",
            "combinedDueDateTime()",
            "function visibleUserOptions()",
            "function userSuggestions()",
            "function knownUsers()",
            "function toggleLabel(label)",
            "function updateLabelLocal(label, assign)",
            "function toggleAttachmentSelection(attachment)",
            "function selectedAttachmentItems()",
            "updated._labelsAuthoritative = true",
            "function assignUser(user)",
            "function unassignUser(user)",
            "function updateAssignedUserLocal(user, assign)",
            "updated._assignedUsersAuthoritative = true",
            "function setCardDone(done)",
            "deckController.assignUser(updated, id, false)",
            'text: page.cardDone() ? i18n.tr("Mark as not done") : i18n.tr("Mark as done")',
            'NextCommon.AppButton',
            "deleteLabelDialog",
            "deckController.deleteLabel(page.selectedLabelForDelete.id)",
        ]:
            self.assertIn(snippet, detail)
        self.assertNotIn('iconName: "reload"', detail)
        self.assertIn("boundsBehavior: Flickable.DragOverBounds", detail)
        self.assertIn("Release to refresh", detail)
        self.assertIn('property string activeTab: "home"', detail)
        self.assertIn("Icon {", detail)
        self.assertNotIn('"icon": "mail-attachment"', detail)
        self.assertIn('"id": "attachments", "label": i18n.tr("Attachments"), "icon": "", "symbol": "\\uD83D\\uDCCE"', detail)
        self.assertIn('"icon": "mail-message-new"', detail)
        self.assertIn('"id": "activity", "label": i18n.tr("Activity"), "icon": "", "symbol": "\\u26a1"', detail)
        self.assertIn("text: modelData.symbol", detail)
        self.assertIn("id: headerTitleField", detail)
        self.assertIn("autoSaveTimer.restart()", detail)
        self.assertIn("function statusIconKind()", detail)
        self.assertIn("function syncStatusDetailsText()", detail)
        self.assertIn('text: i18n.tr("Delete card")', detail)
        self.assertIn('text: i18n.tr("There are no files attached to this card.")', detail)
        self.assertIn("property bool attachmentSelectionMode", detail)
        self.assertIn("onPressAndHold", detail)
        self.assertIn('i18n.tr("%1 selected").arg(page.selectedAttachmentCount())', detail)
        self.assertIn("id: attachFileAction", detail)
        self.assertIn("function attachmentMetadata(attachment)", detail)
        self.assertIn("contentHubBridge.copyImportedFileToCache(fileUrl, fileName)", detail)
        self.assertIn("The selected file could not be prepared for upload.", detail)
        self.assertIn("../backend/DeckAttachmentImportPage.qml", detail)
        self.assertIn("../backend/DeckAttachmentImportPageUbuntu.qml", detail)
        self.assertIn("../backend/DeckAttachmentOpenPage.qml", detail)
        self.assertIn("../backend/DeckAttachmentOpenPageUbuntu.qml", detail)
        self.assertIn("onAttachmentReadyToOpen", detail)
        self.assertNotIn('text: i18n.tr("Load comments")', detail)
        self.assertNotIn("id: titleField", detail)
        api = read_text("qml/backend/DeckApiClient.qml")
        self.assertIn('"duedate": card.duedate || null', api)
        self.assertIn('"done": card.done || null', api)
        self.assertIn("function deleteLabel(serverUrl, userName, secret, boardId, labelId)", api)
        home = read_text("qml/pages/HomePage.qml")
        self.assertIn("function formatDoneDate(value)", home)
        self.assertIn("id: doneBadge", home)
        self.assertIn("font.bold: !page.cardDone(cardItem.cardData)", home)
        self.assertIn('text: "\\u2713 " + page.formatDoneDate(cardItem.cardData.done)', home)
        self.assertIn("function cardLabels(card)", home)
        self.assertIn("function cardAssignedUsers(card)", home)
        self.assertIn("function cardInfoBadges(card)", home)
        self.assertIn("function cardHasDescription(card)", home)
        self.assertIn("function cardAttachmentCount(card)", home)
        self.assertIn("function cardCommentCount(card)", home)
        self.assertIn("id: cardInfoFlow", home)
        self.assertIn('"kind": "description"', home)
        self.assertIn('"kind": "attachments"', home)
        self.assertIn('"kind": "comments"', home)
        self.assertIn('"commentsCount": source.commentsCount', api)
        self.assertIn("dataController.avatarDataUrl(id)", home)
        self.assertIn("dataController.avatarDataUrl(assigneeId)", home)
        self.assertIn("dataController.requestAvatar(assigneeId)", home)
        self.assertIn("id: labelFlow", home)
        self.assertIn("id: assigneeFlow", home)
        self.assertNotIn("accountServerUrl : \"\"", detail)
        self.assertIn("deckController.avatarDataUrl(id)", detail)
        self.assertIn("deckController.avatarDataUrl(assigneeId)", detail)
        self.assertIn("deckController.requestAvatar(assigneeId)", detail)
        picker = read_text("qml/backend/DeckAttachmentImportPage.qml")
        picker_ubuntu = read_text("qml/backend/DeckAttachmentImportPageUbuntu.qml")
        opener = read_text("qml/backend/DeckAttachmentOpenPage.qml")
        opener_ubuntu = read_text("qml/backend/DeckAttachmentOpenPageUbuntu.qml")
        self.assertIn("ContentType.Documents", picker)
        self.assertIn("ContentHandler.Source", picker)
        self.assertIn("signal fileSelected(url fileUrl, string fileName)", picker)
        self.assertIn("ContentTransfer.Charged", picker)
        self.assertIn("ContentTransfer.Collected", picker)
        self.assertIn("import Ubuntu.Content 1.3", picker_ubuntu)
        self.assertIn("ContentType.Documents", opener)
        self.assertIn("ContentHandler.Share", opener)
        self.assertIn("property url fileUrl", opener)
        self.assertIn("ContentTransfer.Charged", opener)
        self.assertIn("import Ubuntu.Content 1.3", opener_ubuntu)
    def test_cache_and_dirty_sync_contract(self):
        cache = read_text("qml/backend/DeckCache.qml")
        controller = read_text("qml/backend/DeckController.qml")
        for snippet in [
            "QtQuick.LocalStorage",
            "CREATE TABLE IF NOT EXISTS boards",
            "CREATE TABLE IF NOT EXISTS stacks",
            "CREATE TABLE IF NOT EXISTS cards",
            "statusCreated",
            "statusEdited",
            "statusDeleted",
            "function loadLocalChanges()",
            "function clearCleanServerDataForCurrentScope()",
            "function markConflict(",
        ]:
            self.assertIn(snippet, cache)
        for snippet in [
            "DeckCache",
            "dirtySyncQueue",
            "dirtySyncRunning",
            "function syncDirtySoon()",
            "function uploadNextDirty(",
            "function continueDirtySyncIfNeeded()",
            "function updateLocalCounts()",
            "cache.saveLocalCard",
            "cache.loadBoardEntries",
            "cache.loadBoards",
            "controller.removeCardEntryByKey(controller.activeDirtyCard.localKey)",
            "function deleteLabel(labelId)",
        ]:
            self.assertIn(snippet, controller)
if __name__ == "__main__": unittest.main()
